name: Learning GitHub Script
on:
  issues:
    types: [opened]

jobs:

  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Comment on new issue
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.PAT}}
        script: |
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🎉 You've created this issue comment using GitHub Script!!!"
            })

    - name: Check Node.js version
      run: node --version
      
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Check Node.js version
      run: node --version

    - name: Add issue to project board
      if: contains(github.event.issue.labels.*.name, 'bug')
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.PAT}}
        script: |
            github.rest.projects.createCard({
            column_id: {{columnID}},
            content_id: context.payload.issue.id,
            content_type: 'Issue'
            });